# Generated by Django 2.2.7 on 2019-11-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.CharField(max_length=500)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stylists', to='hairdressers.Gallery')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stylists', to='hairdressers.Service')),
            ],
        ),
    ]
