# Generated by Django 2.2.7 on 2019-11-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='gallery',
        ),
        migrations.AddField(
            model_name='stylist',
            name='gallery',
            field=models.ManyToManyField(related_name='stylists', to='hairdressers.Gallery'),
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='services',
        ),
        migrations.AddField(
            model_name='stylist',
            name='services',
            field=models.ManyToManyField(related_name='stylists', to='hairdressers.Service'),
        ),
    ]
