# Generated by Django 2.2.7 on 2019-11-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0002_auto_20191113_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
