# Generated by Django 2.2.7 on 2019-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0004_auto_20191114_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='about',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
