# Generated by Django 2.2.7 on 2019-11-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0005_auto_20191114_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='gallery',
        ),
        migrations.AddField(
            model_name='stylist',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stylists', to='hairdressers.Gallery'),
        ),
    ]
