# Generated by Django 2.2.7 on 2019-11-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0006_auto_20191114_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='gallery',
        ),
        migrations.AddField(
            model_name='stylist',
            name='gallery',
            field=models.ManyToManyField(related_name='stylists', to='hairdressers.Gallery'),
        ),
    ]
