# Generated by Django 2.2.7 on 2019-11-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdressers', '0007_auto_20191114_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='stylists', to='hairdressers.Gallery'),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='stylists', to='hairdressers.Service'),
        ),
    ]
